global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'victoria'
    static_configs:
      - targets:
          - localhost:8428
  - job_name: node-exporter
    static_configs:
      - targets : ['node-exporter:9100']
  - job_name: user-service  
    static_configs:
      - targets : ['user-service:8081']